'use client';

import { ArrowRight, FileCode, Plus, Minus } from 'lucide-react';
import type { App, SOP, SubAgent } from '@/lib/mock-data';
import { useEffectiveApp, diffDraftAgainstDeployed, type DiffEntry } from '@/lib/app-state';
import { SpecCopyButton } from './SpecCopyButton';

interface AppSpecProps {
  app: App;
  sop: SOP | undefined;
  subAgents: SubAgent[];
}

function yamlString(v: string): string {
  if (/[:#\[\]{}&*!|>'"%@`,?]/.test(v) || /^\s|\s$/.test(v) || v === '') {
    return JSON.stringify(v);
  }
  return v;
}

function yamlList(items: string[], depth = 2): string {
  if (items.length === 0) return '[]';
  return '\n' + items.map((i) => `${' '.repeat(depth)}- ${yamlString(i)}`).join('\n');
}

interface SpecInput {
  app: App;
  sop: SOP | undefined;
  subAgents: SubAgent[];
  memoryMode: string;
  audience: string;
  customGuardrails: string[];
  deployedVersion: number;
  deployedAt: string | null;
  status: string;
}

function buildSpec({
  app,
  sop,
  subAgents,
  memoryMode,
  audience,
  customGuardrails,
  deployedVersion,
  deployedAt,
  status,
}: SpecInput): string {
  const sopBaselineGuardrails = (sop?.attachedGuardrails ?? []).slice(0, 4);
  const sopCustomGuardrails = (sop?.attachedGuardrails ?? []).slice(4);
  const allCustomGuardrails = [...sopCustomGuardrails, ...customGuardrails];

  const subAgentBlock = subAgents
    .map((sa) =>
      [
        `  - id: ${sa.id}`,
        `    name: ${yamlString(sa.name)}`,
        `    domain: ${yamlString(sa.domain)}`,
        `    description: ${yamlString(sa.description)}`,
        `    tools:${yamlList(sa.toolsBound, 6)}`,
        `    knowledge:${yamlList(sa.knowledgeAttached, 6)}`,
        `    guardrails:${yamlList(sa.guardrailsApplied, 6)}`,
      ].join('\n'),
    )
    .join('\n');

  return [
    `# Generated by Eltropy Studio from ${app.sopFilename}`,
    `# Read-only — edits happen through the Review Studio, then re-derive this spec.`,
    ``,
    `app:`,
    `  id: ${app.id}`,
    `  name: ${app.name}`,
    `  version: ${deployedVersion + 1}`,
    `  status: ${status}`,
    `  description: ${yamlString(app.description)}`,
    `  source_sop:`,
    `    id: ${app.sopId}`,
    `    filename: ${yamlString(app.sopFilename)}`,
    ``,
    `audience:`,
    `  segment: ${audience}`,
    ``,
    `channels:${yamlList(app.channels)}`,
    ``,
    `memory:`,
    `  mode: ${memoryMode}`,
    ``,
    `knowledge:${yamlList(sop?.attachedKnowledge ?? [])}`,
    ``,
    `guardrails:`,
    `  baseline:${yamlList(sopBaselineGuardrails, 4)}`,
    `  custom:${yamlList(allCustomGuardrails, 4)}`,
    ``,
    `sub_agents:`,
    subAgentBlock,
    ``,
    `evaluation:`,
    `  score: ${app.evaluationScore}`,
    `  trend: ${app.evaluationTrend}`,
    `  delta: ${app.evaluationDelta}`,
    `  last_evaluated: ${yamlString(app.lastEvaluatedAt)}`,
    ``,
    `approval:`,
    `  approvals_required: ${app.approvalsRequired}`,
    `  approvals_completed: ${app.approvalsCompleted}`,
    ``,
    `deployment:`,
    `  deployed_version: ${deployedVersion}`,
    `  deployed_at: ${deployedAt ? yamlString(deployedAt) : 'null'}`,
    ``,
  ].join('\n');
}

export function AppSpec({ app, sop, subAgents }: AppSpecProps) {
  const eff = useEffectiveApp(app.id);
  const memoryMode = eff?.memoryMode ?? 'session';
  const audience = eff?.audience ?? 'all_members';
  const customGuardrails = eff?.customGuardrails ?? [];
  const deployedVersion = eff?.deployedVersion ?? app.deployedVersion;
  const deployedAt = eff?.deployedAt ?? app.deployedAt;
  const status = eff?.status ?? app.status;

  const diff = eff ? diffDraftAgainstDeployed(eff) : [];

  const spec = buildSpec({
    app,
    sop,
    subAgents,
    memoryMode,
    audience,
    customGuardrails,
    deployedVersion,
    deployedAt,
    status,
  });

  return (
    <div className="space-y-3">
      {diff.length > 0 && <DiffPanel diff={diff} deployedVersion={deployedVersion} />}

      <section className="rounded-lg border border-border-muted bg-background-subtle overflow-hidden">
        <header className="flex items-center justify-between gap-3 px-4 py-3 border-b border-border-muted">
          <div className="flex items-center gap-2 min-w-0">
            <FileCode className="size-3.5 text-foreground-muted shrink-0" />
            <div className="min-w-0">
              <div className="text-sm font-semibold tracking-tight truncate">
                app.spec.yaml
              </div>
              <div className="text-[11px] text-foreground-muted">
                Read-only · derived from {app.sopFilename}
              </div>
            </div>
          </div>
          <SpecCopyButton text={spec} />
        </header>
        <pre className="px-4 py-4 text-[12px] leading-relaxed font-mono text-foreground overflow-x-auto whitespace-pre">
{spec}
        </pre>
      </section>
    </div>
  );
}

function DiffPanel({ diff, deployedVersion }: { diff: DiffEntry[]; deployedVersion: number }) {
  return (
    <section className="rounded-lg border border-warning/30 bg-warning-subtle/30 overflow-hidden">
      <header className="px-4 py-3 border-b border-warning/20">
        <div className="text-sm font-semibold tracking-tight">
          Pending changes since v{deployedVersion}
        </div>
        <div className="text-[11px] text-foreground-muted mt-0.5">
          Re-submit and re-deploy to publish these. Per FR-DEP-05, edits require re-evaluation and
          re-approval before deployment.
        </div>
      </header>
      <ul className="px-4 py-3 space-y-1.5">
        {diff.map((d, i) => (
          <li key={i} className="flex items-start gap-2 text-xs font-mono">
            {d.kind === 'changed' && (
              <>
                <ArrowRight className="size-3.5 text-warning shrink-0 mt-0.5" />
                <span className="text-foreground-muted">{d.field}:</span>
                <span className="text-error line-through">{d.before}</span>
                <ArrowRight className="size-3 text-foreground-subtle shrink-0 mt-1" />
                <span className="text-success">{d.after}</span>
              </>
            )}
            {d.kind === 'added' && (
              <>
                <Plus className="size-3.5 text-success shrink-0 mt-0.5" />
                <span className="text-foreground-muted">{d.field}:</span>
                <span className="text-success">{d.value}</span>
              </>
            )}
            {d.kind === 'removed' && (
              <>
                <Minus className="size-3.5 text-error shrink-0 mt-0.5" />
                <span className="text-foreground-muted">{d.field}:</span>
                <span className="text-error line-through">{d.value}</span>
              </>
            )}
          </li>
        ))}
      </ul>
    </section>
  );
}
